### ISSUE TITLE
Hidden dependency

### ISSUE THREAD

**Issue by Evizero** [tbreloff/VisualRegressionTests.jl#1]
Right now there is a hidden dependency on FactCheck.jl that is not in requires. Could you maybe be convinced to remove that dependency completely? BaseTestNext, which is going to be the Base.Test of 0.5 (as far as I understand) is pretty good as well

**Comment by tbreloff** [comment]
Yes I think that's a good idea.  I just don't have experience with BaseTestNext and haven't had the chance to learn it yet.

**Comment by Evizero** [comment]
Basically I would suggest that VisualRegressionTests doesn't really need to know about the test framework used by the user. Maybe a simple way to do that is to communicate results just via booleans

**Comment by Evizero** [comment]
I can try sketch out a PR for both issues if you want

**Comment by tbreloff** [comment]
> communicate results just via booleans

I don't see this as an option.  I'd like to get the VisualTestResult object back.  (unless you meant something else)

**Comment by Evizero** [comment]
I meant that one coul replace whatever FactCheck is used for with standard types. Now that I try to find a concrete example, I can't seem to find one. What is FactCheck used for? https://github.com/tbreloff/VisualRegressionTests.jl/blob/master/src/VisualRegressionTests.jl#L10

**Comment by tbreloff** [comment]
You're totally right! I don't use it here.  It's an unnecessary leftover from when I stripped this code out of Plots.
