### ISSUE TITLE
ImageMagick dependency on OSX

### ISSUE THREAD

**Issue by Evizero** [tbreloff/VisualRegressionTests.jl#2]
ref: https://github.com/tbreloff/VisualRegressionTests.jl/commit/9ef657ce7b07df9b528b30a65674c5edd4efae8f#commitcomment-17445749

Right now travis fails for me on OSX because of image magick, which doesn't even seem to serve a purpose there, because QuartzImageIO is there anyhow

**Comment by Evizero** [comment]
mind tagging a new version?

**Comment by tbreloff** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/5167
